// GENERADO — pool de loot v2.0.0 (T5.1): SOLO Gen 1 (#1-151), filtrado del pool #1-200.
// 151 Pokémon repartidos en 4 tiers por poder (cuartiles). Regenerar con el script si cambia.

export const LOOT_POOL_TIERS: Record<1 | 2 | 3 | 4, string[]> = {
  1: ['caterpie', 'weedle', 'magikarp', 'metapod', 'kakuna', 'zubat', 'pidgey', 'rattata', 'spearow', 'diglett', 'jigglypuff', 'nidoran-m', 'nidoran-f', 'paras', 'ekans', 'ditto', 'meowth', 'horsea', 'vulpix', 'sandshrew', 'poliwag', 'bellsprout', 'geodude', 'dratini', 'venonat', 'mankey', 'machop', 'shellder', 'charmander', 'abra', 'doduo', 'gastly', 'squirtle', 'slowpoke', 'bulbasaur'],
  2: ['pikachu', 'oddish', 'psyduck', 'cubone', 'goldeen', 'clefairy', 'magnemite', 'seel', 'grimer', 'krabby', 'exeggcute', 'eevee', 'drowzee', 'voltorb', 'tentacool', 'koffing', 'staryu', 'rhyhorn', 'pidgeotto', 'growlithe', 'omanyte', 'kabuto', 'nidorina', 'nidorino', 'farfetchd', 'poliwhirl', 'onix', 'lickitung', 'weepinbell', 'graveler', 'butterfree', 'beedrill', 'gloom', 'porygon', 'kadabra', 'ivysaur', 'charmeleon', 'wartortle', 'parasect', 'machoke', 'haunter'],
  3: ['ponyta', 'raticate', 'dragonair', 'dugtrio', 'marowak', 'wigglytuff', 'tangela', 'persian', 'seadra', 'fearow', 'arbok', 'sandslash', 'venomoth', 'chansey', 'seaking', 'golbat', 'primeape', 'hitmonlee', 'hitmonchan', 'jynx', 'mr-mime', 'magneton', 'dodrio', 'dewgong', 'kingler', 'pidgeot', 'clefable', 'hypno', 'raichu', 'rhydon', 'vileplume', 'victreebel', 'slowbro', 'electrode', 'weezing'],
  4: ['kangaskhan', 'electabuzz', 'tauros', 'golem', 'magmar', 'omastar', 'kabutops', 'golduck', 'alakazam', 'rapidash', 'muk', 'gengar', 'scyther', 'pinsir', 'nidoqueen', 'nidoking', 'ninetales', 'machamp', 'poliwrath', 'tentacruel', 'aerodactyl', 'starmie', 'venusaur', 'cloyster', 'vaporeon', 'jolteon', 'flareon', 'blastoise', 'exeggutor', 'charizard', 'lapras', 'gyarados', 'snorlax', 'arcanine', 'articuno', 'zapdos', 'moltres', 'dragonite', 'mew', 'mewtwo'],
};
