// GENERADO automáticamente (scripts/genpool) — pool de loot v1.0.0.
// 200 Pokémon (PokeAPI #1-200) repartidos en 4 tiers por poder (suma de stats base, cuartiles).
// No editar a mano: regenerar con el script si cambia el pool.

export const LOOT_POOL_TIERS: Record<1 | 2 | 3 | 4, string[]> = {
  1: ['sunkern', 'caterpie', 'weedle', 'magikarp', 'metapod', 'kakuna', 'pichu', 'igglybuff', 'wooper', 'sentret', 'cleffa', 'zubat', 'togepi', 'spinarak', 'marill', 'hoppip', 'pidgey', 'rattata', 'spearow', 'hoothoot', 'diglett', 'ledyba', 'jigglypuff', 'nidoran-m', 'nidoran-f', 'mareep', 'paras', 'ekans', 'ditto', 'meowth', 'horsea', 'vulpix', 'sandshrew', 'poliwag', 'bellsprout', 'geodude', 'dratini', 'venonat', 'mankey', 'machop', 'shellder', 'charmander', 'cyndaquil', 'abra', 'doduo', 'gastly', 'squirtle', 'totodile', 'slowpoke', 'bulbasaur'],
  2: ['chikorita', 'pikachu', 'oddish', 'psyduck', 'cubone', 'goldeen', 'natu', 'clefairy', 'magnemite', 'seel', 'grimer', 'krabby', 'exeggcute', 'eevee', 'drowzee', 'voltorb', 'chinchou', 'tentacool', 'koffing', 'staryu', 'skiploom', 'rhyhorn', 'pidgeotto', 'growlithe', 'omanyte', 'kabuto', 'aipom', 'nidorina', 'nidorino', 'flaaffy', 'farfetchd', 'poliwhirl', 'onix', 'lickitung', 'weepinbell', 'graveler', 'ledian', 'yanma', 'butterfree', 'beedrill', 'gloom', 'porygon', 'kadabra', 'ariados', 'ivysaur', 'charmeleon', 'wartortle', 'parasect', 'machoke', 'haunter'],
  3: ['bayleef', 'quilava', 'croconaw', 'togetic', 'murkrow', 'ponyta', 'sudowoodo', 'raticate', 'furret', 'dragonair', 'azumarill', 'dugtrio', 'marowak', 'sunflora', 'quagsire', 'wigglytuff', 'tangela', 'misdreavus', 'persian', 'seadra', 'fearow', 'arbok', 'sandslash', 'venomoth', 'chansey', 'seaking', 'noctowl', 'golbat', 'primeape', 'hitmonlee', 'hitmonchan', 'jynx', 'mr-mime', 'lanturn', 'jumpluff', 'magneton', 'dodrio', 'xatu', 'dewgong', 'kingler', 'pidgeot', 'clefable', 'hypno', 'raichu', 'rhydon', 'vileplume', 'victreebel', 'slowbro', 'electrode', 'weezing'],
  4: ['kangaskhan', 'electabuzz', 'tauros', 'bellossom', 'slowking', 'golem', 'magmar', 'omastar', 'kabutops', 'golduck', 'alakazam', 'rapidash', 'muk', 'gengar', 'scyther', 'pinsir', 'politoed', 'nidoqueen', 'nidoking', 'ninetales', 'machamp', 'poliwrath', 'ampharos', 'tentacruel', 'aerodactyl', 'starmie', 'venusaur', 'cloyster', 'vaporeon', 'jolteon', 'flareon', 'meganium', 'espeon', 'umbreon', 'blastoise', 'exeggutor', 'feraligatr', 'charizard', 'typhlosion', 'lapras', 'crobat', 'gyarados', 'snorlax', 'arcanine', 'articuno', 'zapdos', 'moltres', 'dragonite', 'mew', 'mewtwo'],
};
